# This is a basic workflow that is manually triggered

name: Run Python Script Daily

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: python_script

    env:  
      API_BODACC_BASE_URL: ${{ vars.API_BODACC_BASE_URL }}
      EMAIL_FROM_ADRESS: ${{ secrets.EMAIL_FROM_ADRESS }}
      EMAIL_FROM_PASSWORD: ${{ secrets.EMAIL_FROM_PASSWORD }}
      EMAIL_TO_ADRESS: ${{ secrets.EMAIL_TO_ADRESS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.0"

      - name: Install dependencies
        run:
          pip install -r requirements.txt
      
      - name: Debug Variable Injection
        run: echo "🔍 API_BODACC_BASE_URL=${{ vars.API_BODACC_BASE_URL }}"

      - name: Run script
        run: python script.py
      
