# This is a basic workflow that is manually triggered

name: Run Python Script Daily

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "14 23 * * *"
  workflow_dispatch:
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.0"

      - name: Install dependencies
        run:
          pip install -r requirements.txt

      - name: Run script
        run: python script.py
      
